name: tests

on:
  workflow_call:
  pull_request:
    branches:
      - development
      - master
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}-tests"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GIT_STRATEGY: clone
    steps:
    - run: echo "🎉 starting"
    - uses: actions/checkout@v3.5.0
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3
        cache: 'pip'
        cache-dependency-path: |
          wa_services/requirements.txt
    - name: Install Dependencies
      run: |
        echo "🎉 install dependencies"
        python -m pip install --upgrade pip
        pip install -r wa_servies/requirements.txt
    - name: Run Tests
      run: |
        echo "🎉 testing"
        python --version
        python -m black . --check
        pytest -x
        echo "tested"


